function litee(selector){var inst={};if(selector!=document){inst.selector=selector;inst.elements=document.querySelectorAll(selector);inst.length=inst.elements.length;}
inst.inlineTags=['span','a','img','b','strong','i','em','u','big','small','code','sub','sup','button','input','label','select','textarea'];inst.on=function(selectors,callback){var selectors=selectors.split(" "),selector;for(i=0;i<inst.length;i++){inst.thisElement=inst.elements[i];for(ii=0;ii<selectors.length;ii++){selector=selectors[ii];inst.thisElement.addEventListener(selector,callback);}}
return inst;};inst.select=function(index){if(!index){return inst.elements[0].select();}else{return inst.elements[index].select();}};inst.html=function(newContents){if(newContents){for(i=0;i<inst.length;i++){inst.thisElement=inst.elements[i];inst.thisElement.innerHTML=newContents;}
return inst;}else{return inst.elements[0].innerHTML;}};inst.append=function(addContents){for(i=0;i<inst.length;i++){inst.thisElement=inst.elements[i];inst.thisElement.innerHTML=inst.thisElement.innerHTML+addContents;}
return inst;};inst.preAppend=function(addContents){for(i=0;i<inst.length;i++){inst.thisElement=inst.elements[i];inst.thisElement.innerHTML=addContents+inst.thisElement.innerHTML;}
return inst;};inst.value=function(newValue){if(newValue){for(i=0;i<inst.length;i++){inst.thisElement=inst.elements[i];inst.thisElement.value=newValue;}
return inst;}else{return inst.elements[0].value;}};inst.attr=function(name,newContents){if(newContents){for(i=0;i<inst.length;i++){inst.thisElement=inst.elements[i];inst.thisElement.setAttribute(name,newContents);}
return inst;}else{return inst.elements[0].getAttribute(name);}};inst.toggle=function(){for(i=0;i<inst.length;i++){inst.thisElement=inst.elements[i];if(!inst.thisElement.style.display){inst.thisElement.style.display='none';}else{if(inst.thisElement.style.display!='none'){inst.thisElement.style.display='none';}else{if(inst.inlineTags.indexOf(inst.thisElement.tagName.toLowerCase())!=-1){inst.thisElement.style.display='initial';}else{inst.thisElement.style.display='block';}}}}
return inst;};inst.hide=function(){for(i=0;i<inst.length;i++){inst.thisElement=inst.elements[i];inst.thisElement.style.display='none';}
return inst;};inst.show=function(){for(i=0;i<inst.length;i++){inst.thisElement=inst.elements[i];if(inst.inlineTags.indexOf(inst.thisElement.tagName.toLowerCase())!=-1){inst.thisElement.style.display='initial';}else{inst.thisElement.style.display='block';}}
return inst;};inst.boot=function(reqFileName){var xhttp=new XMLHttpRequest();xhttp.onreadystatechange=function(){if(this.readyState==4&&this.status==200){for(i=0;i<inst.length;i++){inst.thisElement=inst.elements[i];inst.thisElement.innerHTML=this.responseText;}}};xhttp.open("GET",reqFileName,true);xhttp.send();return inst;};inst.get=function(reqFileName,callback){var xhttp=new XMLHttpRequest();xhttp.onreadystatechange=function(){if(this.readyState==4&&this.status==200){callback(ajaxContentsResponse=this.responseText);}};xhttp.open("GET",reqFileName,true);xhttp.send();return inst;};inst.post=function(reqFileName,postParams,callback){var postParamsResult="",xhttp=new XMLHttpRequest();for(var pKey in postParams){if(postParams.hasOwnProperty(pKey)){if(postParamsResult==""){postParamsResult=pKey+"="+postParams[pKey];}else{postParamsResult=postParamsResult+"&"+pKey+"="+postParams[pKey];}}}
xhttp.onreadystatechange=function(){if(this.readyState==4&&this.status==200){callback(ajaxContentsResponse=this.responseText);}};xhttp.open("POST",reqFileName,true);xhttp.setRequestHeader("Content-type","application/x-www-form-urlencoded");xhttp.send(postParamsResult);return inst;};return inst;};var $=litee;
